import CyclotomicNT.CyclotomicUnits
import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
import Mathlib.NumberTheory.NumberField.CMField

/-!
# Cyclotomic units of `ℚ(ζ_p)`: the real units `ξ_a` and the eigenspace units `Eᵢ`

Following Washington §8.1–8.3, this begins the cyclotomic-unit group / Vandiver-criterion build
(the deep core of `qiVandiverBridge`).  On top of `CyclotomicNT.cyclotomicUnit` (= `(ζ^a−1)/(ζ−1)`)
we define:
* `realCyclotomicUnit a = ζ^{(1−a)/2}·(ζ^a−1)/(ζ−1)` (Washington's `ξ_a`, real for the
    normalization),
* `eigenCyclotomicUnit i = ∏_{a=1}^{(p−1)/2} ξ_a^{a^{p−1−i}}` (Washington's `Eᵢ`).

The exponent `a^{p−1−i}` is **exactly** the exponent in `CyclotomicNT.QiCert.Qi` and the
    `ζ^{(1−a)/2}`
prefactor is the analogue of `Qi`'s `t^{−kd/2}` — i.e. `Qi` is the mod-`𝔩` image of `Eᵢ`.  This file
defines the objects; their real-ness, the cyclotomic-unit subgroup `C`, the index `[E:C]=h⁺` (to be
axiomatized, Thm 8.2), and the eigenspace criterion (Thm 8.14) come next. -/

namespace CyclotomicNT

open Finset
open scoped NumberField

variable {K : Type*} {p : ℕ} [hpri : Fact p.Prime] [Field K] [CharZero K] [NumberField K]
  [IsCyclotomicExtension {p} ℚ K] {ζ : K} (hζ : IsPrimitiveRoot ζ p)

/-- For `a ∈ [1, (p−1)/2]` and `p` prime, `a` is coprime to `p`. -/
theorem coprime_of_mem_Icc {a : ℕ} (ha : a ∈ Icc 1 ((p - 1) / 2)) : a.Coprime p := by
  rw [mem_Icc] at ha
  refine (hpri.out.coprime_iff_not_dvd.mpr fun hdvd => ?_).symm
  exact absurd (Nat.le_of_dvd (by omega) hdvd) (by omega)

/-- The integer primitive root `ζ ∈ 𝓞 K` as a unit. -/
noncomputable def zetaUnit : (𝓞 K)ˣ :=
  (hζ.toInteger_isPrimitiveRoot.isUnit hpri.out.pos.ne').unit

/-- **Washington's real cyclotomic unit** `ξ_a = ζ^{(1−a)/2}·(ζ^a−1)/(ζ−1) ∈ (𝓞 K)ˣ`
(`1 ≤ a ≤ (p−1)/2`).  The `ζ^{(1−a)/2}` factor is what makes `ξ_a` fixed by complex conjugation
(hence real); proving that is the next brick. -/
noncomputable def realCyclotomicUnit (a : ℕ) (ha : a.Coprime p) : (𝓞 K)ˣ :=
  zetaUnit hζ ^ ((1 - (a : ℤ)) * (((p + 1) / 2 : ℕ) : ℤ)) *
    cyclotomicUnit hζ.toInteger_isPrimitiveRoot hpri.out.two_le ha

/-- **Washington's eigenspace cyclotomic unit** `Eᵢ = ∏_{a=1}^{(p−1)/2} ξ_a^{a^{p−1−i}} ∈ (𝓞 K)ˣ`.
The object of Thm 8.14, and (reduced mod a prime `𝔩 ∣ ℓ`) of `CyclotomicNT.QiCert.Qi`. -/
noncomputable def eigenCyclotomicUnit (i : ℕ) : (𝓞 K)ˣ :=
  ∏ a ∈ (Icc 1 ((p - 1) / 2)).attach,
    realCyclotomicUnit hζ a.1 (coprime_of_mem_Icc a.2) ^ (a.1 ^ (p - 1 - i))

/-- The **cyclotomic unit group** `C ≤ (𝓞 K)ˣ`: the subgroup generated by `-1` and the real
cyclotomic units `ξ_a`.  (Washington §8.1; the index `[E:C] = h⁺` is Thm 8.2, to be axiomatized.) -/
noncomputable def cyclotomicUnitGroup : Subgroup (𝓞 K)ˣ :=
  Subgroup.closure ({-1} ∪ {u | ∃ (a : ℕ) (ha : a.Coprime p), u = realCyclotomicUnit hζ a ha})

omit [CharZero K] [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
theorem realCyclotomicUnit_mem (a : ℕ) (ha : a.Coprime p) :
    realCyclotomicUnit hζ a ha ∈ cyclotomicUnitGroup hζ :=
  Subgroup.subset_closure (Set.mem_union_right _ ⟨a, ha, rfl⟩)

omit [CharZero K] [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
/-- Each eigenspace unit `Eᵢ` lies in the cyclotomic unit group `C`. -/
theorem eigenCyclotomicUnit_mem (i : ℕ) : eigenCyclotomicUnit hζ i ∈ cyclotomicUnitGroup hζ :=
  Subgroup.prod_mem _ fun a _ =>
    Subgroup.pow_mem _ (realCyclotomicUnit_mem hζ a.1 (coprime_of_mem_Icc a.2)) _

omit [CharZero K] [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
@[simp] theorem coe_zetaUnit : (zetaUnit hζ : K) = ζ := by
  rw [zetaUnit, IsUnit.unit_spec]; exact hζ.coe_toInteger

omit [CharZero K] [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
theorem zetaUnit_pow_eq_one : zetaUnit hζ ^ p = 1 := by
  rw [← Units.val_eq_one, Units.val_pow_eq_pow_val, zetaUnit, IsUnit.unit_spec]
  exact hζ.toInteger_isPrimitiveRoot.pow_eq_one

omit [CharZero K] [NumberField K] in
/-- The field coercion of a unit-group `zpow` (the `zpow` lives in `(𝓞 K)ˣ`/`Kˣ`, not `𝓞 K`). -/
theorem coe_units_zpow (u : (𝓞 K)ˣ) (m : ℤ) : ((u ^ m : (𝓞 K)ˣ) : K) = (u : K) ^ m := by
  have h := Units.val_zpow_eq_zpow_val (Units.map (algebraMap (𝓞 K) K : 𝓞 K →* K) u) m
  rw [← map_zpow, Units.coe_map, Units.coe_map] at h
  exact h

omit [CharZero K] [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
/-- **The field value of `ξ_a`**: `ξ_a = ζ^{(1−a)(p+1)/2}·∑_{i<a} ζ^i` (the `(p+1)/2` is `2⁻¹ mod
    p`).
Holds with no `IsCMField` hypothesis — pure computation in `K`. -/
theorem coe_realCyclotomicUnit (a : ℕ) (ha : a.Coprime p) :
    (realCyclotomicUnit hζ a ha : K)
      = ζ ^ ((1 - (a : ℤ)) * (((p + 1) / 2 : ℕ) : ℤ)) * ∑ i ∈ range a, ζ ^ (i : ℤ) := by
  have ht : (algebraMap (𝓞 K) K) hζ.toInteger = ζ := hζ.coe_toInteger
  simp only [realCyclotomicUnit, Units.val_mul, map_mul, coe_units_zpow, coe_zetaUnit,
    coe_cyclotomicUnit, map_sum, map_pow, ht]
  congr 1
  exact sum_congr rfl fun i _ => by rw [zpow_natCast]

section Real

open NumberField.IsCMField

variable [NumberField.IsCMField K]

omit [IsCyclotomicExtension {p} ℚ K] in
/-- Complex conjugation inverts `ζ` (as a unit), since `ζ` is torsion. -/
theorem complexConj_zetaUnit :
    complexConj K (zetaUnit hζ : K) = (zetaUnit hζ : K)⁻¹ := by
  have hfin : IsOfFinOrder (zetaUnit hζ) :=
    isOfFinOrder_iff_pow_eq_one.mpr ⟨p, hpri.out.pos, zetaUnit_pow_eq_one hζ⟩
  exact complexConj_torsion K ⟨zetaUnit hζ, (CommGroup.mem_torsion _).mpr hfin⟩

omit [IsCyclotomicExtension {p} ℚ K] in
include hζ in
theorem complexConj_zeta : complexConj K ζ = ζ⁻¹ := by
  rw [← coe_zetaUnit hζ]; exact complexConj_zetaUnit hζ

open Finset in
omit [IsCyclotomicExtension {p} ℚ K] in
/-- **The real cyclotomic unit `ξ_a` is real** — fixed by complex conjugation; the `ζ^{(1−a)/2}`
normalization is exactly what makes this hold (`a` coprime to `p`, `p` odd). -/
theorem complexConj_realCyclotomicUnit (hp : p ≠ 2) (a : ℕ) (ha : a.Coprime p) :
    complexConj K (realCyclotomicUnit hζ a ha : K) = (realCyclotomicUnit hζ a ha : K) := by
  have hz_ne : ζ ≠ 0 := hζ.ne_zero hpri.out.pos.ne'
  have hz_p : ζ ^ (p : ℤ) = 1 := by rw [zpow_natCast]; exact hζ.pow_eq_one
  have h_coe := coe_realCyclotomicUnit hζ a ha
  have h_reindex : ∑ i ∈ range a, ζ ^ (-(i : ℤ)) =
      ζ ^ (1 - (a : ℤ)) * ∑ i ∈ range a, ζ ^ (i : ℤ) := by
    rw [mul_sum, ← sum_range_reflect (fun i => ζ ^ (-(i : ℤ))) a]
    refine sum_congr rfl fun i hi => ?_
    have hz : ((a - 1 - i : ℕ) : ℤ) = (a : ℤ) - 1 - (i : ℤ) := by
      have := mem_range.mp hi; omega
    rw [hz, ← zpow_add₀ hz_ne]; congr 1; ring
  have hodd : p % 2 = 1 := Nat.odd_iff.mp (hpri.out.odd_of_ne_two hp)
  have H_exp : -((1 - (a : ℤ)) * (((p + 1) / 2 : ℕ) : ℤ)) + (1 - (a : ℤ)) =
      ((1 - (a : ℤ)) * (((p + 1) / 2 : ℕ) : ℤ)) + (p : ℤ) * ((a : ℤ) - 1) := by
    have hdiv : (((p + 1) / 2 : ℕ) : ℤ) * 2 = (p : ℤ) + 1 := by omega
    nlinarith [hdiv]
  have hsum : complexConj K (∑ i ∈ range a, ζ ^ (i : ℤ)) = ∑ i ∈ range a, ζ ^ (-(i : ℤ)) := by
    rw [map_sum]
    exact sum_congr rfl fun i _ => by rw [map_zpow₀, complexConj_zeta hζ, inv_zpow, ← zpow_neg]
  rw [h_coe, map_mul, map_zpow₀, complexConj_zeta hζ, inv_zpow, ← zpow_neg, hsum, h_reindex,
    ← mul_assoc, ← zpow_add₀ hz_ne, H_exp, zpow_add₀ hz_ne, zpow_mul ζ (p : ℤ) ((a : ℤ) - 1),
    hz_p, one_zpow, mul_one]

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The real cyclotomic unit `ξ_a` is a **real unit** — it descends to `𝓞 K⁺`. -/
theorem realCyclotomicUnit_mem_realUnits (hp : p ≠ 2) (a : ℕ) (ha : a.Coprime p) :
    realCyclotomicUnit hζ a ha ∈ realUnits K := by
  obtain ⟨v, hv⟩ := (Units.complexConj_eq_self_iff (u := realCyclotomicUnit hζ a ha)).mp
    (complexConj_realCyclotomicUnit hζ hp a ha)
  refine (mem_realUnits_iff (u := realCyclotomicUnit hζ a ha)).mpr ⟨v, ?_⟩
  apply FaithfulSMul.algebraMap_injective (𝓞 K) K
  rw [IsScalarTower.algebraMap_apply (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K) K] at hv
  exact hv

omit [IsCyclotomicExtension {p} ℚ K] in
/-- Each eigenspace unit `Eᵢ` is a real unit. -/
theorem eigenCyclotomicUnit_mem_realUnits (hp : p ≠ 2) (i : ℕ) :
    eigenCyclotomicUnit hζ i ∈ realUnits K :=
  Subgroup.prod_mem _ fun a _ =>
    Subgroup.pow_mem _ (realCyclotomicUnit_mem_realUnits hζ hp a.1 (coprime_of_mem_Icc a.2)) _

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **The cyclotomic unit group `C` consists of real units** — `C ≤ realUnits K`, i.e. `C` descends
to the maximal real subfield `K⁺` (Washington §8.1: `C ⊆ E = 𝓞(K⁺)ˣ`). -/
theorem cyclotomicUnitGroup_le_realUnits (hp : p ≠ 2) :
    cyclotomicUnitGroup hζ ≤ realUnits K := by
  rw [cyclotomicUnitGroup, Subgroup.closure_le]
  rintro u (hu | ⟨a, ha, rfl⟩)
  · rw [Set.mem_singleton_iff] at hu; subst hu
    rw [SetLike.mem_coe, mem_realUnits_iff]
    exact ⟨-1, by simp⟩
  · exact realCyclotomicUnit_mem_realUnits hζ hp a ha

end Real

end CyclotomicNT
